### ISSUE TITLE
[references suggestion] the “R Inferno” book

### ISSUE THREAD

**Issue by phineas-pta** [gagolews/deepr#1]
hello,

thank you for your works

i just want to suggest the book “R Inferno”, especially its chapter 8 which contains a lot of tricks and quirks of R.

best wishes for a happy new year 😊

**Comment by gagolews** [comment]
Thank you for the suggestion – I will check it out at some point.

**Comment by gagolews** [comment]
I'll add a citation thereto + some exercises in the upcoming release. Thanks.
