### ISSUE TITLE
section 9.3.2 Dollar "Nonstandard names must still be enclosed in backticks:" -- single and double quotes work well

### ISSUE THREAD

**Issue by J-Moravec** [gagolews/deepr#11]
In section 9.3.2 Dollar, `$` (*), for the following code:

```
x <- list(spam="a", eggs="b", `eggs and spam`="c", best.spam.ever="d")
```

deeper says that:

> Nonstandard names must be enclosed in backticks

However, single and double quotes work in place of backticks as well. At least for subsetting from objects.

The following operations are equivalent:
```
x$`eggs and spam`
x$"eggs and spam"
x$'eggs and spam'
``` 

So are these:
```
x <- list(spam="a", eggs="b", `eggs and spam`="c", best.spam.ever="d")
x <- list(spam="a", eggs="b", 'eggs and spam'="c", best.spam.ever="d")
x <- list(spam="a", eggs="b", "eggs and spam"="c", best.spam.ever="d")
```

(great book btw., looking towards the minimalistic pipelines!)

**Comment by gagolews** [comment]
Ahoj Jiří! You're right, thanks! Fix on the way.
