### ISSUE TITLE
Typo in introduction 1.1

### ISSUE THREAD

**Issue by lh** [gagolews/deepr#12]
Trivial typo but might confuse someone:

1.1 Introduction "Documenting code is a good development practice. It is thus worth knowing that any text **followed by** a hash sign (that is not part of a string) is a comment. It is ignored by the interpreter."

Should probably be, "Documenting code is a good development practice. It is thus worth knowing that any text **following** a hash sign (that is not part of a string) is a comment. It is ignored by the interpreter."

**Comment by gagolews** [comment]
Thanks! Fix on the way.
