### ISSUE TITLE
Typo «ligua franca» (Preface, 0.3, p. XV)

### ISSUE THREAD

**Issue by DEKapinos** [gagolews/deepr#15]
Hi, Marek!

«Our aim is to learn the fundamentals of base R, which constitutes the **ligua franca** for all R users.» (Preface, 0.3, p. XV).

Should be «lingua franca», I guess.

Thanks for the book!

With best regards,
Dmitry Kapinos

**Comment by gagolews** [comment]
Thanks for spotting this; fix on the way.
