### ISSUE TITLE
The wording may need an editing (ch. 2, 2.1.4, exercise 2.1, p. 17)

### ISSUE THREAD

**Issue by DEKapinos** [gagolews/deepr#16]
Hi, Marek!

«Exercise 2.1 Take a look at the manual page of seq_along and seq_len. **Determine** Having
seq3 at hand, **determine** whether they can easily be done without.» (p. 17).

It seems, that first «determine» is redundant.

P.S. Also the sentence as a whole seems incomplete: «they can be easily done without» <what?>.

I think the question is: whether the same functionality can be easily done just with seq() without implementation of the separate functions, am I right?

With best regards,
Dmitry Kapinos

**Comment by gagolews** [comment]
Indeed, thanks. Fix on the way.
