### ISSUE TITLE
Exercise 14.4 may need to suggest changing package name.

### ISSUE THREAD

**Issue by Nerwosolek** [gagolews/deepr#17]
In exercise 14.4 there is a need to also change the line in `helloworld2.cpp` from:
`invisible(.Call("C_hello", PACKAGE="helloworld"))`
to:
`invisible(.Call("C_hello", PACKAGE="helloworld2"))` - PACKAGE name should be changed.

You may want to add this suggestion to exercise description along others.

And thanks for your work!

**Comment by gagolews** [comment]
Thanks, fix on the way!
