### ISSUE TITLE
Exercise 4.1 - problem with y <- sample(c(FALSE, TRUE), n)

### ISSUE THREAD

**Issue by mesykkor** [gagolews/deepr#19]
I tried copy/paste into my code and got:

_> y <- sample(c(FALSE, TRUE),1000)
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'_

Intuitively, it should do exactly what intended: draw 1000 samples from c (FALSE,TRUE), however, I had to add replace=TRUE to obtain samples in the requested dimension.

Perhaps, y <- as.logical(rbinom(n, 1, 0.5)) may offer a solution as well and allow to play with the proportion of TRUE/FALSE like you suggested in another exercise. On the other hand an illustration of sample() behavior is also valuable.

Thanks for a good book and have a nice weekend,

Mojmir

**Comment by gagolews** [comment]
Thanks for spotting this error.

Indeed, `replace=TRUE` is the missing element.

Fix is on the way.
