### ISSUE TITLE
A few typos 

### ISSUE THREAD

**Issue by dyavorsky** [gagolews/deepr#21]
First, great book!  Thank you for making it available online and low-cost in print.  I especially appreciate your personality that comes out in phrases like "the whole garbage dump called the internet" :)

Typos, most involving apostrophes:

1. Section 3.2.3, hardcopy page 41: 'due to the numbers' being written" -- numbers' should have no apostrophe 
2. Exercise 4.10, hardcopy page 66: "which work with objects' textual representation in the form executable R code" -- make representation plural (representations) and add "of" so that it reads "representation**s** in the form **of** executable R code"
3. Section 6.1.1, hardcopy page 95:  "due to some **fonts'** being missing" -- no apostrophe on fonts
4. Section 9.1.2, hardcopy page 158:  "the default **functions'** behavior" -- I would change functions' to function (the default function behavior)
5. Section 7.2.1, hardcopy page 119: "returned as other function's outputs" -- move the apostrophe (other functions' outputs) or use "another" (another function's output) 
6. Section 7.2.3, hardcopy page 120: **cummmin** is spelled with one too many m's (should be cummin)
7. Section 7.3.1, hardcopy page 134: there is inconsistent use of bold for package naming, specifically in the phrase "using the pkg::object syntax" which has pkg bold but it should not be
8. Example 8.5 on hardcopy page 141 seems like it should be Exercise 8.4 (an **exercise**, not an example)
9. Section 9.2.4, hardcopy page 164: "For instance, we can run a package build, install, and check process **is possible** on every git commit."  Delete the "is possible" part.
10. Exercise 9.22 is about data.frames which aren't introduced until chapter 12.
11. Section 9.4.2 on hardcopy page 175: "**an** temporary" should be "a temporary"
12. Section 10, footnote 1:  "ordinary ('old S') R" which I think should be "ordinary ('old R') S".

A comment on chapter 9.  After an **extremely** well organized first section of the book, the reader is tossed into chapter 9, titled "Designing Functions".  However, most of sections 9.1 and 9.2 are not necessarily related to designing functions, and each topic there is only introduced at a cursory level.  For example, on page 163, we are told that "during run time, we can redirect stdout and stderr to different files or even strings using sink."  The typical reader will not know what stdout or stderr are, and no example is provided on how to use sink() to perform the indicated redirection.  Similarly, the topic of writing packages comprises an entire book by Hadley Wickham; here, it is relegated to the two pages of section 9.2.2.  Similarly, on page 164, debugging is mentioned as a thing one could do, and left at that, with virtually no detail.  My suggestion is to reorganize chapter 9 into two chapters: one on designing functions and another on "introducing additional components" (such as debugging, package development, or interaction with a shell/terminal) so that the reader is prepared for a potpourri of topics, each introduced but not necessarily expanded upon.

**Comment by gagolews** [comment]
Thanks, Dan! I'll correct the above soon.
