### ISSUE TITLE
Chapter 3.2.3. could mention `all.equal()`

### ISSUE THREAD

**Issue by fkohrt** [gagolews/deepr#5]
For numeric equality it is recommended to test via `isTRUE(all.equal(x, y))`, which could be mentioned in chapter [3.2.3. Dealing with round-off errors](https://deepr.gagolewski.com/chapter/130-logical.html#dealing-with-round-off-errors) (and maybe also in the first note in chapter 3.3.4.).

**Comment by gagolews** [comment]
Thanks. I mention it in one of the exercises at the end of chapter 3 – as a topic for "self study".
