### ISSUE TITLE
Missing period and alternative to `registerS3method`

### ISSUE THREAD

**Issue by fkohrt** [gagolews/deepr#6]
Hi, thanks for your fine book, which I'm currently skimming. While reading sometimes I notice things which I could write down here, but please tell me if you feel there's no need for it.

Two points:

1. The fourth paragraph in chapter [9.1.1.](https://deepr.gagolewski.com/chapter/210-design.html#checking-input-data-integrity-and-argument-handling) maybe has a period missing:
   > This is why it is better to keep the vocabulary quite restricted Even if there are exceptions to the general rules, with fewer functions, they are easier to remember. We advocate for such minimalism in this book.
2. The note in chapter [10.2.6](https://deepr.gagolewski.com/chapter/220-s3.html#operator-overloading) says that one might need to use `registerS3method()`. The documentation at `help("registerS3method", "base")` says, however, that it is “not intended to be called directly”. As an alternative, the method `.S3method()` can be used (see also Kurt Hornik: [S3 Method Lookup](https://blog.r-project.org/2019/08/19/s3-method-lookup/index.html)). Exercise [16.15](https://deepr.gagolewski.com/chapter/330-environment.html#id47) might also need updating.

**Comment by gagolews** [comment]
Thanks, I'll fix that when I'm back from holidays. :)

**Comment by gagolews** [comment]
Sorry for a late response, my holiday-ing got out of control. But back now I am.

Yes, if you have found more bugs like this, don't hesitate to report them – any form will do. Thanks!
