### ISSUE TITLE
Cryptic footnote in Chapter 2

### ISSUE THREAD

**Issue by IndrajeetPatil** [gagolews/deepr#7]
I couldn't figure out what the second sentence is getting at here: 

<img width="1208" alt="Screenshot 2023-11-29 at 21 56 09" src="https://github.com/gagolews/deepr/assets/11330453/c70e8d02-1d9e-4527-aaf0-bbfb1395d5d0">

**Comment by gagolews** [comment]
Thanks for reporting this. Changing to:

> {command}`min`, {command}`median`, and {command}`max` are generalised by the {command}`quantile` function. We will discuss it much later ({numref}`sec:special-attributes`), because it returns a *named* vector.
